const ACTION_ACTIVATION = {
  ACTIVATE_GADGET : "ACTIVATE_GADGET",
  GADGET_ACTIVATED : "GADGET_ACTIVATED",
  ACTIVATION_FAILED : "ACTIVATION_FAILED"
};

const ACTION_LOGIN = {
  LOGGING_IN: "LOGGING_IN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED"
};

const ACTION_LOGOUT = {
  LOGGING_OUT: "LOGGING_OUT",
  LOGGED_OUT: "LOGGED_OUT",
  LOGOUT_FAILED: "LOGOUT_FAILED"
};

export {
  ACTION_ACTIVATION,
  ACTION_LOGIN,
  ACTION_LOGOUT
};